extends:
  - next
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
  - prettier

rules:
  import/order:
    - error
    - pathGroups:
        - pattern: "@/**"
          group: "external"
          position: "after"

settings:
  import/resolver:
    typescript:
      project: ./tsconfig.json
